name: Bookworm API CI

on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USER }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASS }}
        run: |
          docker build -f api/dockerfile -t ghcr.io/rhezaas/bookworm-api:latest api/
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          docker push ghcr.io/rhezaas/bookworm-api:latest
