name: Bookworm API CI

on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -f api/dockerfile -t ghcr.io/rhezaas/bookworm-api:latest api/
          echo ${{ secrets.REGISTRY_PASS }} | docker login ghcr.io -u ${{ secrets.REGISTRY_USER }} --password-stdin
          docker push ghcr.io/rhezaas/bookworm-api:latest
